### ISSUE TITLE
The problem with the rule `prefer-const`

### ISSUE THREAD

**Issue by mrmlnc** [SamVerschueren/vscode-linter-xo#10]
I have a problem with rule `prefer-const` ([prefer-const](http://eslint.org/docs/rules/prefer-const)) in this plugin.

For example:

```js
function getJsonData() {
  let obj = {};

  return obj;
}

getJsonData('test');
```

My config in `package.json`:

```json
  "xo": {
    "rules": {
      "indent": [2, 2, { "SwitchCase": 1 }],
      "no-var": 2,
      "prefer-const": [2, { "destructuring": "all" }],
      "arrow-parens": [2, "always"],
      "object-curly-spacing": [2, "always"],
      "babel/object-curly-spacing": 0,
      "space-before-function-paren": [2, "never"],
      "generator-star-spacing": [2, "after"]
    },
    "globals": [
      "use",
      "chai"
    ],
    "envs": [
      "browser",
      "node",
      "mocha",
      "jquery"
    ]
  }
```

The output of XO CLI:

![image](https://cloud.githubusercontent.com/assets/7034281/15819193/64c9f86c-2bea-11e6-98a7-ae2bdf42dbfc.png)

The output of this plugin:

![image](https://cloud.githubusercontent.com/assets/7034281/15819235/af22d6d6-2bea-11e6-99e2-d0006651d0cb.png)

Thank you for this plugin.

**Comment by SamVerschueren** [comment]
Are you sure you enabled the plugin? https://github.com/SamVerschueren/vscode-linter-xo#settings

**Comment by mrmlnc** [comment]
@SamVerschueren yes,
![image](https://cloud.githubusercontent.com/assets/7034281/15819945/b1c6f012-2bee-11e6-8909-686e03f7c9e2.png)

**Comment by SamVerschueren** [comment]
That's odd, it works correctly for me. Could you remove the XO config in `package.json`, reload the window, and see if it's still not working?

What's the version output of the following commands?

```
$ xo --version
$ node_modules/.bin/xo --version
```

**Comment by mrmlnc** [comment]
Oh, @SamVerschueren, sorry.

I forgot that the rules in `package.json` will be overridden by rules in the preferences editor.

**Comment by SamVerschueren** [comment]
No problem, glad it is resolved :)
