### ISSUE TITLE
XO should clear errors if a file gets closed

### ISSUE THREAD

**Issue by mrmlnc** [SamVerschueren/vscode-linter-xo#11]
Source: https://github.com/Microsoft/vscode-eslint/issues/94

> We removed some bogus code for 1.3.x from the core which cleared markers on buffer close. We had to remove that to get to a consistent project build story. Now the producer of markers must ensure to clear them if they re not needed anymore (was the contract always)

```js
documents.onDidClose((event) => {
  connection.sendDiagnostics({ uri: event.document.uri, diagnostics: [] });
});
```

**Comment by SamVerschueren** [comment]
Thanks @mrmlnc

**Comment by mrmlnc** [comment]
@SamVerschueren, maybe you publish a new version? :yum:

**Comment by SamVerschueren** [comment]
Sorry, done :)
