### ISSUE TITLE
Only passes saved contents to XO Fix

### ISSUE THREAD

**Issue by wmertens** [SamVerschueren/vscode-linter-xo#13]
To run XO Fix, you first have to save the file. If not, it will overwrite your pending changes with the fixed version of the file on disk.

To reproduce:
1. Edit a file, change
2. XO Fix
3. Your changes are removed

**Comment by SamVerschueren** [comment]
Seems to work for me though. Or am I doing something wrong?

![xo-fix](https://cloud.githubusercontent.com/assets/1913805/16903097/4a628692-4c74-11e6-90d9-b9637896620f.gif)

**Comment by wmertens** [comment]
Aargh! I was testing the previous version :( I had updated and restarted but apparently the update didn't take. Sorry for the noise, working as it should! 👍

**Comment by SamVerschueren** [comment]
Ah, I'm glad it's fixed. No problem, those things happen ;).
