### ISSUE TITLE
Does not take overrides into account

### ISSUE THREAD

**Issue by wmertens** [SamVerschueren/vscode-linter-xo#19]
I have a subdir of a project with different rules, defined under xo.overrides, and when I run XO from the command line it works fine, but in VSCode it uses the main configuration, even when running the fix.

**Comment by SamVerschueren** [comment]
Could you show me the directory structure? Where are those overrides defined? In a `package.json` file?

**Comment by wmertens** [comment]
It's defined exactly as described at https://github.com/sindresorhus/xo#config-overrides

Not sure what to show you :) a subdir of the project has different rules…

**Comment by SamVerschueren** [comment]
So it's just one `package.json` in the root of your project which defines some `xo.overrides` for files in a subdirectory?

**Comment by wmertens** [comment]
correct.

**Comment by SamVerschueren** [comment]
Could you check again. Seems it didn't work in `gulp-xo` as well and had to be fixed in `XO` itself. https://github.com/sindresorhus/gulp-xo/issues/10#issuecomment-249800305

**Comment by wmertens** [comment]
:tadaa: :+1:

**Comment by SamVerschueren** [comment]
Sweet! :)
