### ISSUE TITLE
Fix `Path must be a string. Received null` error

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/vscode-linter-xo#20]
I believe this error is caused by this plugin. It happens when you open files in the Git view of the editor.

<img width="1011" alt="screen shot 2016-10-20 at 16 02 40" src="https://cloud.githubusercontent.com/assets/1913805/19562963/a8b4ad06-96de-11e6-824c-a94f7f308663.png">

**Comment by mariosant** [comment]
I confirm that, happens to me as well.

**Comment by jshamley** [comment]
I also get this error, but for me it happens in all views of the editor.

**Comment by SamVerschueren** [comment]
Fixed in `2.1.1`.

@jshamley It shouldn't happen in every view, only in the Git view. So if this release didn't fix it for you, make sure it's because of this extension by disabling all the others. If it still keeps showing, feel free to open a new issue. But I'm not sure if I will be able to solve it as it never happened to me in the `Explorer` view.

**Comment by simonhaenisch** [comment]
I am `2.2.0` now and get almost the same error when opening a git diff, but with `undefined` instead of `null`:

> Path must be a string. Received undefined
