### ISSUE TITLE
command xo.fix not found on Mac OSX

### ISSUE THREAD

**Issue by kristianmandrup** [SamVerschueren/vscode-linter-xo#21]
I installed `linter-xo` via `ext install`, then enabled it and restarted VSC. 
However, I get: `command xo.fix not found` Any idea why?

**Comment by SamVerschueren** [comment]
You mean the keyboard binding `xo.fix`? If not, in the command palette it's XO > fix

**Comment by kristianmandrup** [comment]
How do I set up a keyboard binding to `xo.fix` then?

**Comment by SamVerschueren** [comment]
`Code > Preferences > Keyboard Shortcuts` and add something like this to your `keyboards.json`.

```json
{
	"key": "alt+f",
	"command": "xo.fix"
}
```
