### ISSUE TITLE
Very slow

### ISSUE THREAD

**Issue by wmertens** [SamVerschueren/vscode-linter-xo#22]
I don't know if this is the linter, xo or some plugin, but XO results are extremely slow. It is as if every keystroke results in a lint, instead of only linting if the previous run completed and the text is dirty again.

On "larger" files (400 lines) this becomes very noticeable, taking tens of seconds/minutes.

Anything I can do to troubleshoot?

**Comment by SamVerschueren** [comment]
Thanks for reporting @wmertens. Personally, I never had issues with this. You can easily check if it's this plugin since the new release (1.7) as you can easily disable the other extensions. Mind doing that and check this again?

**Comment by wmertens** [comment]
I have no ieda what was happening but it stopped happening. I'll close this and investigate more if it happens again.

**Comment by SamVerschueren** [comment]
Thanks for following up!

**Comment by wmertens** [comment]
It's happening again :) I think it started when I upgraded XO in the project, and indeed, in another project XO is fast.

Any ideas for how to troubleshoot?

**Comment by lsunsi** [comment]
Just to add to the issue, I have a somewhat big project and I'm having performance issues as well. Really sluggish. Any ideas?

**Comment by luizParreira** [comment]
Same here, having performance issues on large files. Any ideas on how to improve performance? 😄

**Comment by luisfmsouza** [comment]
The same here. I've recorded a gif about it:

![delayed-xo](https://user-images.githubusercontent.com/4405147/39641104-6f16d9be-4fa3-11e8-85c8-17e868b6223c.gif)

**Comment by xlc** [comment]
I have fixed the performance issue with #35 but seems like this repo is no longer maintained.
So I published it myself https://marketplace.visualstudio.com/items?itemName=bryan-chen.linter-xo-2

**Comment by SamVerschueren** [comment]
It still is maintained, just had other things on my mind.

**Comment by SamVerschueren** [comment]
@xlc if you want I can add you as a maintainer of this project. Let me know if you would be interested.
