### ISSUE TITLE
Plug-in not working?

### ISSUE THREAD

**Issue by Jamerrone** [SamVerschueren/vscode-linter-xo#23]
Hey guys,
I have been trying to get this plug-in working for quite some time, and no success yet. I am quite new at this so it is probably my own fault. Also xo linter works just fine using the cmd, and yes I have the plug-in installed and it is enabled in the user settings. My map structure looks like this:

node_modules
-- .bin
-- xo
main.js
package.json

My package.json looks like:

```
{
  "name": "xo-linter-test",
  "version": "1.0.0",
  "scripts": {
    "test": "xo"
  },
  "devDependencies": {
    "xo": "^0.17.1"
  },
  "xo": {
    "semicolon": false
  }
}
```

And user settings:

```
{
  "css.validate": false,
  "editor.tabSize": 2,
  "stylelint.enable": true,
  "workbench.statusBar.visible": false,
  "xo.enable": true
}
```

**Comment by SamVerschueren** [comment]
This is very odd. It's like the most minimal example, it should definitely work. I have actually no clue for now why it's failing. After initialising the project, have you restarted VS Code and reloaded the project?

**Comment by Jamerrone** [comment]
Yes, multiple times, I even restarted my pc. I could try to reinstall vsCode itself, but that will have to wait a bit.

**Comment by SamVerschueren** [comment]
Have you tried disabling the other extensions to make sure it doesn't interfer? Since the latest version you can do that quite easily.

**Comment by Jamerrone** [comment]
Ok, so I got it working now, but I have no idea what was going on, I reinstalled vsCode and installed every extension again, it din't work. I disabled all my extensions other than XO, and it worked! After that I enabled every single extension again but it still worked. Strange but I am happy with it.

**Comment by SamVerschueren** [comment]
Let's close the issue. If you experience it again, let me know.

**Comment by pixelass** [comment]
I can't get xo to work either. 

minimal setup. 

VS code  1.13.1 (1.13.1)

I added linter-xo and stylelint. stylelint works but xo doesn't

Everything else is vanilla.


```json
{
	"stylelint.enable": true,
    "xo.enable": true,
    "css.validate": false,
    "scss.validate": false,
    "less.validate": false
}
```

**Comment by SamVerschueren** [comment]
Have you installed the XO dependency in your project?

**Comment by pixelass** [comment]
related to https://github.com/sindresorhus/xo/issues/234

**Comment by pixelass** [comment]
Everything is set up correctly. In my case it is probably related to the size of the project. 
Due to an issue with XO I added a testing and linting suite (separate pacjakge.json) in a deeply nested folder (this is where we lint and test)  This was working on VSCode.

We now use eslint with the xo-shared-config and everything works fine in various editors our developers use.

I'm pretty sure this is related to xo itself and not this olugin. 

Thanks so far

**Comment by pixelass** [comment]
Also stated here #32
