### ISSUE TITLE
Incorrect current working dir

### ISSUE THREAD

**Issue by camilleriluke** [SamVerschueren/vscode-linter-xo#26]
I have encountered the following situation when using this plugin. I am not sure if this is the intended behaviour however, in case it is not, I am also suggesting a fix for this.

## Current problem

Seems like that the plugin is using the file's (being tested) dir path as the current working directory ([source](https://github.com/SamVerschueren/vscode-linter-xo/blob/master/xo-server/src/server.ts#L183)) when composing the XO options hash.

This is causing an issue when XO tries to determine the applicable override for the file ([source](https://github.com/sindresorhus/xo/blob/master/index.js#L18))

### Testing repo

Here is a repo https://github.com/camilleriluke/cuddly-succotash that shows this.

According to the setting specified in the [package.json](https://github.com/camilleriluke/cuddly-succotash/blob/master/package.json) all files should be indented with 2 spaces while anything that matches `test/*.js` should be indented with 3 spaces.

With the [current implementation](https://github.com/SamVerschueren/vscode-linter-xo), it seems that the overrides are not being respected.

## Proposed solution

Use the worksapce root and the current working dir when composing the options hash. This will work well when XO will assemble the filename ([source](https://github.com/sindresorhus/xo/blob/master/index.js#L16)) and try to find the applicable override configuration.

**Comment by SamVerschueren** [comment]
Released as `2.1.3`. Seems to work perfectly now! :beers:
