### ISSUE TITLE
Upgrade to use ValidationQueue

### ISSUE THREAD

**Issue by JonnyBurger** [SamVerschueren/vscode-linter-xo#29]
This repo should upgrade to `vscode-languageserver@3`, which has a new feature: `ValidationQueue`.

## Why?
Currently, whenever a file changes, the xo lint gets triggered. When a file changes multiple times quickly, it is not necessary anymore to lint files that are outdated, but this is the current behaviour. This makes the extension slower and leads to errors briefly showing up that don't exist anymore.

## How?
`vscode-eslint` is an example of a module that takes advantage of `ValidationQueue`. It could be used as a reference.
An upgrade to v3 of `vscode-languageserver` is necessary, this version has a few breaking changes. So this extension would also at least have to change to use `.onReady()` ([v3 Changelog](https://github.com/Microsoft/vscode-languageserver-node#breaking-changes)).

**Comment by SamVerschueren** [comment]
Cool! Help appreciated though!

**Comment by wmertens** [comment]
I believe this may also alleviate #22

**Comment by SamVerschueren** [comment]
Yes I believe it is. Don't really have much time to look into this. So any help is more than welcome. Might find some time in the coming weeks.

**Comment by JonnyBurger** [comment]
FYI, I have tried to tackle this recently, here is my progress: https://github.com/SamVerschueren/vscode-linter-xo/compare/master...JonnyBurger:v3-upgrade

However, I did not manage to close it out. It's just so hard to debug, I can't get `console.log` to work. (Does anyone have any suggestions for that?)

My attempt involved the following:

- Upgrade to `vscode-languageserver@3` and `vs-languageclient@3` so that we have access to ValidationQueue
  - Changes with `DiagnosticSeverity`, `RequestType`, `client.protocol2CodeConverter ` result from this because those were breaking changes
- Ended up implementing my own queue though, because I thought the Microsoft one has some sort of caveat (don't remember what exactly it was though, tbh)

**Comment by SamVerschueren** [comment]
Yes it's pretty hard to debug. You should be able to attach a debugger but honestly, I never got it working. At some point, I just wrote output to a text file in order to debug it. I know, not best practice but I had to do something right :).

**Comment by JonnyBurger** [comment]
Hello, I just wanted to let you know that I am not going to further work on this. I wanted to do this for a long time, but now I think it's just easier to move to plain eslint with the xo config instead.

Thanks for the help though and hopefully my comments also will make it easier to improve performance!

**Comment by SamVerschueren** [comment]
Fixed by #35
