### ISSUE TITLE
How do you install this extension to VSCode?

### ISSUE THREAD

**Issue by kevinfiol** [SamVerschueren/vscode-linter-xo#30]
Nowhere in the README do you actually instruct how to install this into VSCode. You only say you must have XO installed already, which I do.

**Comment by SamVerschueren** [comment]
Like any other extension in VS Code. There's not much to it to be honest...

**Comment by kevinfiol** [comment]
Gee, thanks for the help.

**Comment by SamVerschueren** [comment]
Would a section like this help? https://github.com/SamVerschueren/vscode-final-newline#install

**Comment by kevinfiol** [comment]
Yes, thank you!!!!!

**Comment by SamVerschueren** [comment]
Fixed. Thanks for the suggestion. Sorry for the my first reply, wasn't meant to be rude...
