### ISSUE TITLE
Fails when file contains eslint-disable* comments

### ISSUE THREAD

**Issue by akshendra** [SamVerschueren/vscode-linter-xo#33]
Linter fails with the following message if the file contains eslint-disable* style comments.

```
Notification handler 'textDocument/publishDiagnostics' failed with message: Illegal argument: line must be positive
```

I have encountered this for `eslint-disable` and `eslint-disable-line`.

**Comment by SamVerschueren** [comment]
I cannot reproduce this issue. Can you provide an example js file where you get this error?

**Comment by akshendra** [comment]
Seems to not happening anymore

**Comment by SamVerschueren** [comment]
Thanks for letting us know :)!
