### ISSUE TITLE
Cannot find how to run this plugin on html or json files.

### ISSUE THREAD

**Issue by plumpNation** [SamVerschueren/vscode-linter-xo#34]
Is there a setting for this I am missing somewhere?

```
{
    ...
    "xo": {
        "space": 4,
        "semicolon": true,
        "envs": [
            "browser",
            "mocha"
        ],
        "globals": [
            "expect"
        ],
        "plugins": [
            "html"
        ],
        "settings": {
            "html/indent": "+4"
        },
        "rules": {
            "unicorn/filename-case": [
                "error",
                {
                    "case": "pascalCase"
                }
            ]
        }
    }
}
```

**Comment by SamVerschueren** [comment]
The extension is only activated for [js and jsx](https://github.com/SamVerschueren/vscode-linter-xo/blob/master/xo/package.json#L27-L28).

**Comment by plumpNation** [comment]
Is support on the roadmap for json and "js in html" aka script tags?

**Comment by lagden** [comment]
@SamVerschueren 

Can you put `html` and `vue`?

To [SublimeLinter-contrib-xo](https://github.com/sindresorhus/SublimeLinter-contrib-xo/pulls) I send a PR...

if wish I can do the same for you...

**Comment by plumpNation** [comment]
OK, I'm going to close this then. Thanks for the plugin.

**Comment by SamVerschueren** [comment]
Sorry guys. Feel free to send a PR. Have lots of other stuff on my mind.
