### ISSUE TITLE
not working in vs code 1.18.1

### ISSUE THREAD

**Issue by achal7** [SamVerschueren/vscode-linter-xo#36]
Getting below error in output window.
[Error - 21:01:52] Request textDocument/codeAction failed.
  Message: Unhandled method textDocument/codeAction
  Code: -32601 

In current folder i have only 1 js file. The same project works if I run xo from command line, it works as expected, shows errors, warnings, fix them.

However as a VS Code tool its not working.

**Comment by xlc** [comment]
textDocument/codeAction is fixed by #38
