### ISSUE TITLE
cannot find eslint-plugin-react

### ISSUE THREAD

**Issue by Pszek** [SamVerschueren/vscode-linter-xo#4]
I get the error message: "cannot find eslint-plugin-react". I installed xo both locally and global and eslint-react-plugin locally only (and I would like to stay it that way).

**Comment by SamVerschueren** [comment]
Have you configured XO to use the plugin?

**Comment by Pszek** [comment]
Thanks for quick response. Yes, I used plugins array in xo config placed in package.json.

**Comment by SamVerschueren** [comment]
Have you used `react` as value or `eslint-plugin-react`?

**Comment by Pszek** [comment]
```JSON
"xo": {
  "extends": "xo-react",
  "plugins" : [
    "react",
    "babel"
  ],
  "rules": {
    "babel/arrow-parens": 0,
    "react/jsx-closing-bracket-location": [
      2,
      "tag-aligned"
     ],
   }

Please look at essential fragments from my config

**Comment by SamVerschueren** [comment]
Thanks, this is helpfull. Will have a look late today.

**Comment by SamVerschueren** [comment]
This is odd, it works fine on my machine. Just copy-pasted some React example.

![screenshot](https://cloud.githubusercontent.com/assets/1913805/13549550/d94969ec-e307-11e5-96c9-5a470073e024.gif)

This is my `xo` configuration in `package.json`

```json
"xo": {
  "extends": "xo-react",
  "plugins": [
    "react"
  ]
}
```

My dev-dependencies:
- eslint-config-xo-react
- eslint-plugin-react

Can you take a screenshot of the error message? Curious where it shows that error.

**Comment by Pszek** [comment]
![untitled](https://cloud.githubusercontent.com/assets/10253750/13549885/8a40a47e-e310-11e5-8217-f3b847b50bb6.gif)

Also on the left pane my dependencies.

**Comment by SamVerschueren** [comment]
That's odd. What happens when you run `xo` on that project from the terminal?

**Comment by Pszek** [comment]
Yep it fails. So  it is not Your add on issue. Closing issue.

**Comment by SamVerschueren** [comment]
Try `rm -rf node_modules && npm install` to make sure you have all the dependencies.

**Comment by Pszek** [comment]
done that. I think I messed something after updating to npm 3 or devDependencies.

**Comment by Pszek** [comment]
Reopnening (earlier resigned from using VSC, but now I use it again).
XO in other editors as well as in CLI works. I 've got still the same problem 'cannot find eslint-plugin-react'.
Is there a way I can turn on debugging for linter (like in Atom), so it would be easier to find a cause?

**Comment by Pszek** [comment]
this is eslint issue
