### ISSUE TITLE
Error "No parser could be inferred for file: <text>"

### ISSUE THREAD

**Issue by jorgegonzalez** [SamVerschueren/vscode-linter-xo#48]
![image](https://user-images.githubusercontent.com/12901172/41320927-b430be08-6e6f-11e8-868e-592c54bdab75.png)

This error only appears on files that are named `cli.js`.

If I rename the file to something else it goes away. But it will pop up again when changed back to `cli.js`.

Very strange.

**Comment by jorgegonzalez** [comment]
Now it's happening in a bunch of random files. Trying to find a similarity.

**Comment by SamVerschueren** [comment]
You are 100% sure it's this extension? Have you disabled all other extensions? I've cut a new release yesterday so it might be a bug on our side, just wanted to be sure.

**Comment by jorgegonzalez** [comment]
Yes

![image](https://user-images.githubusercontent.com/12901172/41329918-725db9d4-6e9e-11e8-9584-9982b8f509eb.png)

That's with every other extension disabled

**Comment by jorgegonzalez** [comment]
Maybe because this project is a monorepo?

**Comment by SamVerschueren** [comment]
Do you have a `package.json` file in the root of your project?

**Comment by jorgegonzalez** [comment]
Yes and that’s where my xo config is.

**Comment by xlc** [comment]
This error text seems come from prettier
https://github.com/prettier/prettier/blob/1350edc5a65bded15b9dfc27d5e2a0706d9d1fe1/src/main/options.js#L46
What is your xo config?

**Comment by jorgegonzalez** [comment]
Yep turning off Prettier makes this error go away.

```json
"xo": {
	"space": 2,
	"prettier": true
}
```

**Comment by jorgegonzalez** [comment]
Any progress?

**Comment by SamVerschueren** [comment]
Just leave it open, it might be a valid issue, didn't have time to look into yet.

**Comment by simonhaenisch** [comment]
I experience the same issue when enabling prettier in my xo config (in `package.json`):

```json
{
  "xo": {
    "prettier": true
  }
}
```

But it only happens to the files that I have in a folder called `scripts`. If I rename `scripts` to something else, the problem disappears :roll_eyes:

**Comment by jorgegonzalez** [comment]
Any update on this? This error has never really gone away.
