### ISSUE TITLE
Pass `filename` to lintText

### ISSUE THREAD

**Issue by sindresorhus** [SamVerschueren/vscode-linter-xo#5]
See https://github.com/sindresorhus/SublimeLinter-contrib-xo/commit/35bb3d3579b7ef072b3f41b686c1e504dc8702ab#diff-6c1f4f1574c85da37dc4dd59341c9a39R15 and https://github.com/sindresorhus/atom-linter-xo/commit/e4fbc732bb469cddfec16eadcc681669c1143dd5

This is needed by some ESLint rules.

-

Btw, unrelated, but you could simplify this https://github.com/SamVerschueren/vscode-linter-xo/blob/ceee4cf11577301eba1bfd40a2113e287974461c/xo-server/server.ts#L133-L137 as `results` is always 1 item when using `lintText`. See: https://github.com/sindresorhus/atom-linter-xo/blob/1f9a769fc0fd41459802a3e4a8358ea5a234820f/index.js#L48

**Comment by SamVerschueren** [comment]
Thanks Sindre for reporting this, much appreciated :)!

> as results is always 1 item when using lintText

Nice, didn't know that.

**Comment by sindresorhus** [comment]
> Nice, didn't know that.

I didn't either some hours ago https://github.com/sindresorhus/atom-linter-xo/commit/f760f70885402f4ef1d45d6a706caf5c1e797105#diff-168726dbe96b3ce427e7fedce31bb0bcL49. It makes sense since `lintText` only accepts a string (1 file).

**Comment by SamVerschueren** [comment]
Thanks Sindre for keeping me up-to-date ;). There is a VS Code issue a.t.m. that keeps me from releasing a new version but as soon as that is addressed, a fix is being released.

**Comment by SamVerschueren** [comment]
Released 💃
