### ISSUE TITLE
How do I disable linter-xo for typescript?

### ISSUE THREAD

**Issue by simonhaenisch** [SamVerschueren/vscode-linter-xo#53]
## Setup:

I have a Javascript project that I lint with XO and within that project I have a `firebase/functions` directory for Firebase cloud functions, written in Typescript.

```
project
|-- firebase/functions
    |-- package.json
    |-- tslint.json
|-- package.json
```

`firebase/functions/tslint.json` is basically `{ "extends": "tslint-xo" }`.

## Problem:

I don't want the `linter-xo` extension to lint my typescript file, because it doesn't lint it properly, e. g. for `const y = (x: number) => x` it reports

```
[XO] Parsing error: Unexpected token :
```

I tried setting `"xo": { "extensions": [ "js" ] }` in my `package.json` as well as in the VS Code setting (`"xo.options"`), but the linter still lints my Typescript files. I also tried `"xo": false` in `firebase/functions/package.json`, but that didn't work either.

---

I assume that the way to solve this is to use `tslint` for `firebase/functions` instead, however I can't disable `linter-xo` for Typescript and the file gets linted by both.

Alternatively, is there a way of making `linter-xo` work for typescript (so I don't need `tslint` and `tslint-xo`)?

**Comment by xlc** [comment]
try `"xo.options": { ignores: ["**/*.ts", "**/*.tsc"] }`

https://github.com/xojs/xo#ignores

**Comment by simonhaenisch** [comment]
Thanks, ignoring works.

Just in case someone else has a similar setup, I also had to set

```
"typeRoots": ["node_modules/@types"]
```

in `firebase/functions/tsconfig.json`, otherwise the build complained about missing dom lib types for the types in the root project (`../../node_modules/@types`).
