### ISSUE TITLE
Parsing error: File '/tsconfig.json' not found.

### ISSUE THREAD

**Issue by fnky** [SamVerschueren/vscode-linter-xo#61]
When using vscode-linter-xo, the linter shows the following message:

```
[XO] Parsing error: File '/tsconfig.json' not found.
```

This is represented as a popup in the editor at the first occurence like so:

![A screenshot of VSCode showing the error message "[XO] Parsing error: File '/tsconfig.json' not found."](https://user-images.githubusercontent.com/995050/51804685-5e8ec680-2264-11e9-958a-fce219e48825.png)

I am using the following configurations:

##### package.json

```json
{
  "name": "test-xo",
  "version": "1.0.0",
  "scripts": {
    "lint": "xo"
  },
  "devDependencies": {
    "@sindresorhus/tsconfig": "^0.2.0",
    "@types/node": "^10.12.18",
    "@typescript-eslint/eslint-plugin": "1.1.0",
    "eslint-config-xo-typescript": "^0.6.0",
    "tslint": "^5.12.1",
    "tslint-xo": "^0.13.0",
    "typescript": "^3.2.2",
    "xo": "^0.24.0"
  },
  "xo": {
    "extends": "xo-typescript",
    "extensions": [
      "ts"
    ]
  }
}
```

##### tsconfig.json

```json
{
  "compilerOptions": {
    "outDir": "dist",
    "target": "es2017",
    "rootDir": "source",
    "baseUrl": ".",
    "moduleResolution": "node",
    "types": [
      "node"
    ],
    "allowJs": true,
    "declaration": false
  },
  "include": [
    "source"
  ]
}
```

##### User Settings

```json
{
  "tslint.enable": true,
  "editor.formatOnSave": true,
  "xo.enable": true,
  "xo.format.enable": true
}
```

#### Additional notes

- Running XO from the command-line works correctly.
- I have disabled all extensions and other formatters except for XO.

**Comment by markypython** [comment]
What's the status of this?

**Comment by CvX** [comment]
@markypython #65 fixes this, but @SamVerschueren has to review that PR. 🙂
