### ISSUE TITLE
XO Fix => empty file

### ISSUE THREAD

**Issue by wmertens** [SamVerschueren/vscode-linter-xo#7]
When I run XO Fix, it clears the file.

That certainly resolves all issues though not in the way I was hoping 😉

**Comment by SamVerschueren** [comment]
Noticed this as well. Make sure the file is not dirty by just saving it and run `XO Fix` again. Does that work? Might be an issue with dirty files.

**Comment by wmertens** [comment]
Figured it out: if there was no change, it deletes the contents. So that's a small bug to fix.

Note that the Atom linter doesn't require that the file is saved: https://github.com/sindresorhus/atom-linter-xo/blob/master/index.js#L100-L120

**Comment by SamVerschueren** [comment]
Aha, good catch! Thanks for investigating.

**Comment by SamVerschueren** [comment]
It seems this is a little bit more work then I thought. They added a bunch of new features since I created this plugin so I have to refactor it drastically. Not much time a.t.m. but keep you posted.

**Comment by kaasdude** [comment]
+1

**Comment by SamVerschueren** [comment]
Released `v2.0.0` which should fix this issue. Please reopen if you still experience some issues with it.

**Comment by wmertens** [comment]
I can't reopen, but the issue is still there :-/

To reproduce:
1. XO Fix
2. Save
3. XO Fix
