### ISSUE TITLE
Error when enabling Browser envs in XO config

### ISSUE THREAD

**Issue by KsRyY** [SamVerschueren/vscode-linter-xo#70]
When I specify
``` json
"env": {
	"browser": true
}
```
in the XO config, the extension says `def.split is not a function or its return value is not iterable`

**Comment by KsRyY** [comment]
It seems like enabling any `env` will cause this error

**Comment by andrewdbond** [comment]
For others experiencing this issue, I was able to successfully _add_ an env by [putting it in the package.json](https://github.com/xojs/xo#user-content-config) or [with the `xo --env` option](https://github.com/xojs/xo#user-content-usage).


The [documentation says this configuration option defaults](https://github.com/xojs/xo#user-content-envs) to `['es2021', 'node']`. However, even if I only listed `["es2021"]` in package.json or with the --env option, it never seemed to turn off or change any node-related options at least in the `xo --print.config` output.

Attempting to use `xo --env.node false` also produced an immediate error.
