### ISSUE TITLE
Support editor.codeActionsOnSave

### ISSUE THREAD

**Issue by arnohovhannisyan** [SamVerschueren/vscode-linter-xo#80]
With the ESLint, TSLint, and StyleLint extensions, there are code actions that fix all auto-fixable problems when saving. It would be great if this extension supported it as well.

## Example

```js
// settings.json

{
  "editor.codeActionsOnSave": {
    "source.fixAll.xo": true
  }
}
```

**Comment by sheedy** [comment]
@arnohovhannisyan It works with these settings:

```json
"xo.enable": true,
"xo.format.enable": true,
"editor.defaultFormatter": "samverschueren.linter-xo",
"[javascript]": {
  "editor.formatOnSave": true,
  "editor.codeActionsOnSave": {
    "source.fixAll": true
  },
  "editor.defaultFormatter": "samverschueren.linter-xo"
}
```

I also duplicate the `[javascript]` for `[javascriptreact]`.
