### ISSUE TITLE
Fails with no details

### ISSUE THREAD

**Issue by slikts** [SamVerschueren/vscode-linter-xo#81]
XO 0.30.0
Extension 2.3.3
VSCode 1.45.0-insider

Error:

> Command 'XO: Fix all auto-fixable problems' resulted in an error (Running the contributed command: 'xo.fix' failed.)

Running the XO script from the command line works, however.

**Comment by jopdeklein** [comment]
@slikts I had the same issue, it was fixed for me by enabling the plugin (I had assumed this was the default).

![Screenshot 2020-06-09 at 11 50 15](https://user-images.githubusercontent.com/200943/84133411-6e690e00-aa47-11ea-9500-3faf26fb798d.png)

**Comment by yakov116** [comment]
@slikts still have an issue?
