### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by osdiab** [SamVerschueren/vscode-linter-xo#86]
It hasn't been updated in a year despite lots of issues; is anyone still managing this/is this still a recommended tool for XO? The native ESLint VSCode plugin has gotten pretty good over time, supports newer stuff like `yarn berry`, and more so it's a bummer to see this essential part of the `xo` ecosystem remain unloved, pushing me to ditch `xo` and just set everything up by hand again as I would have. cc @sindresorhus @SamVerschueren

**Comment by sikhote** [comment]
The plugin is no longer available on vscode, so I guess not using XO anymore :(

**Comment by sholladay** [comment]
I'd be happy to contribute $ to revive this project, if there is a maintainer who has time for it. My team has run into some of the known bugs, which makes XO a tough sell at work.

**Comment by SamVerschueren** [comment]
I'm happy to add people as maintainer. So if anyone is willing to take it, let me know.

**Comment by Spence-S** [comment]
Lots of updates coming soon! see #95
