### ISSUE TITLE
2-space formatting tends to convert tabs into more tabs.

### ISSUE THREAD

**Issue by m4bwav** [SamVerschueren/vscode-linter-xo#9]
When I try to autofix spacing issues when converting from tabs to 2-space npm style the spacing gets ruined with extra tabs or spaces.

**Comment by SamVerschueren** [comment]
The only thing this extension does is pass the `fix` command to [XO](https://github.com/sindresorhus/xo) which on his turn passes the `fix` command to `ESLint`. So this is an `ESLint` issue, not an issue with this extension so I'd suggest to file a bug at the ESLint repo.

**Comment by m4bwav** [comment]
Alright, my bad.

**Comment by SamVerschueren** [comment]
No problem :)
